### PR TITLE
unpack vis/tango_vi.llb, extensively adopt typedefs, little code refact

### PR DESCRIPTION
**Pull request by EastEriq**
* tango_vi.llb has been unpacked and all the individual files dispatched to subfolders under /visrc, matching the virtual folder names originally listed in tango.lvlib. Compiled code has been removed from all vis. Source control would be pretty ineffective without this.

--> Please note that there were some 100 VIs not cathegorized at all in the original lvlib. I dumped all of them in a new subfolder visrc/Orphan with descendants, they should be sorted more logically.

--> Note that there are several Typedefs subfolder, not all of them containing only typedefs, and .ctl files in other folders. Some reorganization may be due.

* a project visrc/build_library.lvproj has been created. Its main purpose is to rebuild automatically the packed file tango_vi.llb should that be needed for compatibility with existing applications (my bet is that it shouldn't if things have been done correctly). The build specification can be part of the package release process.

--> the file tango_vi.llb itself is a derived artefact and can be therefore removed from source control.

* Some new typedefs have been created; typedefs have been extensively used in the existing vi codebase.

--> Common VIs/Typedefs/_AttributeDataType_t.ctl and Orphan/Typedefs/_DataType.ctl seem to refer to the same type, they should be probably unified in all their callers.

--> Common VIs/Typedefs/_TangoDataType_t.ctl, which is a different enumerator than the previous two, might have a misleading name, and might be renamed.

--> Common VIs/Typedefs/_CmdArgDataType_t seems unreferenced.

* As an example of code factorization, a few instances (e.g. the first alphabetically) in Client VIs/Private VIs/Attributes/Readers have been reworked and simplified. The exercise could be carried on extensively there and elsewhere.

--> it is possible that polymorphic VIs like _TangoReadAttributes.vi can be much more compactly rewritten as a read-anything-to-LV-variant. Type information will thus become an integral part of the variant wire, eliminating the need for so many polymorph instances (at the price of dealing with variants and Variant to Data in applications)

* The code has been minimally cleaned up when I happened to be on it, e.g. reordering controls on the FP according to the conpane, removing unnecessary sequence frames and iteration counts for autoindexed loops, straightening bent wires, etc.

* The codebase has been checked for no broken VI, but no unit test has been performed, nor compatibility with existing VI application software could be tested.

### CODE REVIEW

**Comment by nleclercq** [comment]
Thanks for the PR. I just gave it a try and I'm quite impress by the result in terms of side effects on the existing code - I don't see any regression - at least with the provided client and server examples. Congrats for that.  

My main concern is now focused on the "orphan" vis. For instance, why did you moved the _DServerDevicePropertyToXXXX.vi to the orphan repository? These are supposed to be part of the _DServerGetDeviceProperty.vi polymorphic vi. The same apply to _DServerGetRawDeviceProperty.vi which is called from all _DServerDevicePropertyToXXXX.vi.  The fact that a vi is not categorized in the original lvlib doesn't mean that is useless or unused - it's simply hidden. But ok, for symmetry reasons they should appear under a 'Server VIs/Private VIs'.    

BTW, tell me if I'm wrong but your "read-anything-to-LV-variant" (_TangoReadAttributes.vi) doesn't seem to respect our main constraint: backward compatibility. The current implementation is used in hundreds of apps and must remain as it is.

**Comment by EastEriq** [comment]
Ok thanks.

` I don't see any regression - at least with the provided client and server examples.`
I take it that for now I don't need to run the example tests myself too, will set them up if I carry on the work.

`For instance, why did you moved the _DServerDevicePropertyToXXXX.vi to the orphan repository? etc.`
I just ran a script which moved to Orphan any vi which was not referenced in the virtual folders of the original library, that's all. Subsequently I created manually a few subfolders, but just as a first attempt.
Now, any folder structure is fine, and whichever should work, provided only that the relevant files are correctly referenced in the .lvlib. For good order it is nice if the virtual folders match exactly the file paths on the disk, but that is not even mandatory. So certainly, Server VIs/Private is a relevant group for some of these orphans. Even Server VIs/Private/Instances or whatever. The easiest is to move around groups of files within the labview project, that way references and ownerships are kept in sync.

`BTW, tell me if I'm wrong but your "read-anything-to-LV-variant" (_TangoReadAttributes.vi) doesn't seem to respect our main constraint: backward compatibility.`
Certainly. It is just an idea for the future, might lead to leaner code which is easier to maintain, but is not a replacement.

**Comment by nleclercq** [comment]
`The easiest is to move around groups of files within the labview project, that way references and ownerships are kept in sync.`

Sorry, but can you be more explicit please. I don't see what you mean.

**Comment by EastEriq** [comment]
I just mean, to open the lvlib in labview, and both drag and drop files or groups of files in and out of virtual folders when in _Items_ view, and Move on Disk groups of files when in _Files_ view.
spazio di lavoro 1_009
This way Labview keeps track of dependencies and keeps the files owned by the library. Moving files externally, and attempting to reconstruct later missing dependencies or conflicting library ownerships, may turn in a dependency hell, for experience.

**Comment by nleclercq** [comment]
@EastEriq How do you remove compiled code from vis?

**Comment by EastEriq** [comment]
In a project, right click on the root item in the project tree, select Properties. You have the option of marking individually project items for removal.
In a library, right click on the root of the library/Properties. I see a single checkbox, I'm not sure if the setting is then propagated to all members or to new ones or what.
In any event I happen to have a script for it lying around here.
[SeparateCompiledCodeTree.vi.zip](https://github.com/tango-controls/labview-binding/files/1987634/SeparateCompiledCodeTree.vi.zip)

**Comment by nleclercq** [comment]
Ok. Thanks.

Here's what I've done so far:
- merged your PR into a new branch called `visRefactoring`
- moved orphan VIs to appropriate directories (following your method - see above)
- moved `visrc` to root directory - `vis` being used for binary distribution
- committed changes to `visRefactoring`

Once everything is fine, I will merge our mods to the master.

**Comment by EastEriq** [comment]
I see. It seems you have forgotten to remove the former vis/visrc from repo, it is still in the code tree. Otherwise I quickly checked, the llb builds fine on my side.
BTW what about 
> Common VIs/Typedefs/_AttributeDataType_t.ctl and Orphan/Typedefs/_DataType.ctl seem to refer to the same type, they should be probably unified in all their callers.

**Comment by nleclercq** [comment]
> BTW what about
> 
> Common VIs/Typedefs/_AttributeDataType_t.ctl and Orphan/Typedefs/_DataType.ctl seem to refer to >the same type, they should be probably unified in all their callers.

Should be fixed now. 
From now on, we are using _AttributeDataType_t.ctl (_DataType.ctl removed).

BTW, I restored vis/tango_vi.llb so that guys can give the binding a try without having to rebuild the labview project. Any objection?

**Comment by EastEriq** [comment]
> Should be fixed now.
> From now on, we are using _AttributeDataType_t.ctl (_DataType.ctl removed).

will check tomorrow

> BTW, I restored vis/tango_vi.llb so that guys can give the binding a try without having to rebuild the labview project. Any objection?

makes +8MB and duplicates code at two different locations, probably running off visrc would be fine as well as long as tango_vi.lvlib is referenced, but you're the boss [I mean, you know what other old installations are out there and would break, I really don't]

>the former vis/visrc from repo, it is still in the code tree.

they are still in and have to be deleted, obviously, to avoid confusion

**Comment by nleclercq** [comment]
> makes +8MB and duplicates code at two different locations, ...

I added a "How to build the VIs library" section to the README.md. However, since the C++ binaries are provided, I would prefer to keep the llb in the repo (for symmetry reasons) - unless its presence generates some side effects. Future will tell...

**EDIT: I'm finally going to remove the whole binary stuffs from the source repo (including the runtime) and build binary distributions that I will upload on github as dedicated projects.** 

> they are still in and have to be deleted, obviously, to avoid confusion

Fixed.

**Comment by nleclercq** [comment]
Finally removed any binary stuff from the github repo - including the tango llb. The Tango binary software chain is now provided as an optional package attached to the [latest release](https://github.com/tango-controls/labview-binding/releases). The README.md has been updated accordingly.

**Pull request merged**
