### PR TITLE
finish modularization of attribute readers, read attribute in variant

### PR DESCRIPTION
**Pull request by EastEriq**
read as variant is a proposal for augmentation. My use case:
v

### CODE REVIEW

**Comment by nleclercq** [comment]
Created a dedicated branch in order to give this PR a try.

**Comment by nleclercq** [comment]
@EastEriq What is the idea behind the variant approach?

**Comment by EastEriq** [comment]
That the programmer does not have to know a priori which type the attribute is, to select the proper polymorphic instance. Besides, like in my snippet, there are cases where a generic value can be passed to a generic data sink, and in LV that is done with variants. In my example I have different indicators of different types, and one single variant read VI suits all. LV runtime errors would result if the variant type would not be compatible with the indicator type; but thus mismatches can be handled as runtime rather than edit time errors.

**Comment by nleclercq** [comment]
I see. That's what I imagined. In fact the underlying implementation (i.e. the one behind the polymorphic VIs) is generic and used "bunch of bytes" representation. The polymorphic VIs is just made of "casts" to the proper (or expected) data type. So you just added a Variant cast to the existing polymorphic read Vi, right ?

**Comment by EastEriq** [comment]
I just copied each of the unpackings of the bytes (toXXX.vi) in a case structure with 38 cases (see toVariant.vi). The eventual elegance is in the use of the top VI, not in its internals. LV types do not map to tango types nor viceversa, so I think any solution would have involved ad hoc code; "cast" in LV sense is not directly possible. If anything I could perhaps have used the names of the tango types (e.g. SPE->1D array, LONG->32bit etc.) to construct a mapping grid, but I felt it was a vane effort.

**Comment by nleclercq** [comment]
Can you provide a usage example please? You could push it in the examples lvproj of the new 'readasVariant' branch. Thanks.

**Comment by EastEriq** [comment]
I resist the zeal of splitting also examples.llb and creating a project for examples.lvlib. So, instead of blowing up the repo +2.5MB for nothing, what would you think of this?
[VariantAttributeReadExample.vi.zip](https://github.com/tango-controls/labview-binding/files/2048179/VariantAttributeReadExample.vi.zip)

**Comment by EastEriq** [comment]
> I resist the zeal of splitting also examples.llb and creating a project for examples.lvlib

Ok so I did that too, it's in the master branch of my fork. Now the tree is under examples/examples.src/, you can move it around as you think it fit. Includes the VI above.

**Comment by nleclercq** [comment]
Would you mind creating a pull request for the examples library? You can do it on the master. I will then apply it to the readasVariant branch. Thanks.

**Comment by nleclercq** [comment]
Thanks for the PR.

**Pull request merged**
